version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/talgat/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name

networks:
  app-network:
    driver: bridge
