version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/talgat/ssl/ssl.crt:/etc/nginx/ssl/ssl.crt
      - /home/talgat/ssl/ssl_private.key:/etc/nginx/ssl/ssl_private.key
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
